[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "src/netlify/functions"

[functions.refresh-market-data]
  schedule = "@daily"

[functions.refresh-news]
  schedule = "@daily"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, s-maxage=60, stale-while-revalidate=300"
